dataset: CIFAR100_LT
train_epochs: 100
num_experts: 100
zca: True
buffer_path: ../buffer_storage
data_path: ../dataset
rho_max: 0.01
rho_min: 0.01
alpha: 0.3
lr_teacher: 0.01
mom: 0.
batch_train: 256
parall_eva: False
imbalance_rate: 0.1
align_with_long_tail: False
expert_oversampling: False
class_balanced_loss: False

save_dir: ../buffer_storage/CIFAR100_LT/imbalance_rate_01/first_stage_weight_balancing_GSAM_mom_0_l2_5e-3/
log_file_path: ../buffer_storage/CIFAR100_LT/imbalance_rate_01/first_stage_weight_balancing_log_GSAM_mom_0_l2_5e-3.txt

GSAM: True
# first stage
first_stage_expert: True
l2: 5e-3
first_stage_cutmix: False
first_stage_cutmix_prob: 0.5
beta: 1.0

# second stage
second_stage_expert: False
second_stage_maxnorm: False

test: False