dataset: Tiny_LT
res: 64
model: ConvNetD4
device: [0,1,2,3,4,5,6,7]

ipc: 10
syn_steps: 25
syn_steps_second: 25
expert_epochs: 2
zca: True
lr_teacher: 0.01
buffer_path: ../buffer_storage/
data_path: ../dataset
ema_decay: 0.9995
Iteration: 10000
batch_syn: 500

# wandb
project: Tiny_LT

num_eval: 1
eval_it: 500
skip_first_eva: True
Momentum_y: 0.9
threshold: 10.
pix_init: real

batch_train: 128
Sequential_Generation: False

lr_img: 100
lr_lr: 0.0001
lr_y: 10.0

min_start_epoch: 10
max_start_epoch: 50
second_min_start_epoch: 0
second_max_start_epoch: 1

# long tail
imbalance_rate: 0.1
noise: False
duplicate: True
hard_label: False
align_with_long_tail: False

# match stage
first_stage_expert_dir: ../buffer_storage/TinyImageNet_LT/imbalance_rate_01/first_stage_weight_balancing_GSAM_mom_0_l2_5e-3
second_stage_expert_dir: ../buffer_storage/TinyImageNet_LT/imbalance_rate_01/second_stage_weight_balancing_GSAM_mom_0_l2_5e-3

# first stage
first_stage_expert: False
weighted_loss: True
BFLoss: False
first_weight_factor: 0.
first_stage_lambda: 1.
match_classifier: False
# second stage
second_stage_weighted_loss: False
second_stage_lambda: 0.1